version: "3.9"
services:
  quakejs:
    environment:
      - HTTP_PORT=8080
    ports:
      - '8080:80'
      - '27960:27960'
    image: 'treyyoder/quakejs:latest'
    #https://hub.docker.com/r/treyyoder/quakejs -> https://github.com/treyyoder/quakejs-docker