version: "3.9"
services:
  app:
    build: .
    ports:
      - 8080:8080

  db:
    image: postgres:14-alpine
    # ports:
    #   - 5432:5432
    environment:
      - "POSTGRES_USER=db_user"
      - "POSTGRES_PASSWORD=db_pwd"
      - "POSTGRES_DB=demo"
    volumes:
      - data:/var/lib/postgresql/data 

volumes:
  data: